### ISSUE TITLE
Error in Build id: N20141117-2000 without the feature patch

### ISSUE THREAD

**Issue by vogella** [trylimits/Eclipse-Postfix-Code-Completion#11]
Build id: N20141117-2000 should have the JDT patches https://git.eclipse.org/c/jdt/eclipse.jdt.ui.git/commit/?id=2a4886c69e3ac30b76571020a4c1e87694106c8b and  http://git.eclipse.org/c/jdt/eclipse.jdt.core.git/commit/?id=75afdf2996a1c8ae6b0b5be7d9f9b9919d6b66a0 in it.

If I run Tail Completion without the JDT feature patch in this build I get the following error.

java.lang.IllegalAccessError: tried to access field org.eclipse.jdt.internal.ui.text.template.contentassist.TemplateEngine.fContextType from class org.eclipse.jdt.postfixcompletion.core.PostfixTemplateEngine
    at org.eclipse.jdt.postfixcompletion.core.PostfixTemplateEngine.complete(PostfixTemplateEngine.java:41)
    at org.eclipse.jdt.internal.ui.text.java.AbstractTemplateCompletionProposalComputer.computeCompletionProposals(AbstractTemplateCompletionProposalComputer.java:66)
    at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:333)
    at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:337)
    at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:325)
    at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:282)
    at org.eclipse.jface.text.contentassist.ContentAssistant$5.run(ContentAssistant.java:1904)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1902)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:573)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:570)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:505)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:499)
    at org.eclipse.jface.text.contentassist.ContentAssistant.showPossibleCompletions(ContentAssistant.java:1720)
    at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor$AdaptedSourceViewer.doOperation(CompilationUnitEditor.java:183)
    at org.eclipse.ui.texteditor.ContentAssistAction$1.run(ContentAssistAction.java:82)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.ui.texteditor.ContentAssistAction.run(ContentAssistAction.java:80)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
    at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:122)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
    at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:286)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:507)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:558)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:378)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:324)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:86)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1574)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1387)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1412)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1397)
    at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1424)
    at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:824)
    at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3283)
    at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:773)
    at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2098)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:5524)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:4697)
    at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
    at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9137)
    at org.eclipse.swt.widgets.Display.eventProc(Display.java:1253)
    at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
    at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2482)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3411)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:648)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:592)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

**Comment by trylimits** [comment]
Thanks for the report.

The applied changes in the 4.5 release do not completely match our feature patch, i.e. the protected fields as they are in our feature patch have become protected getter-methods. Therefore the current implementation is not running in 4.5 without some changes.
I already have a adapted the implementation for 4.5 in my local repo, however, I'm not sure about the best release strategy (if possible: 1 update site for Luna/Mars, Luna w feature patch, Mars w/o, slightly different implementations). Recommendations?

Nevertheless, I will push the changes for 4.5 to a new branch today or tomorrow.

**Comment by vogella** [comment]
> I'm not sure about the best release strategy (if possible: 1 update site for Luna/Mars, Luna w feature > patch, Mars w/o, slightly different implementations). Recommendations?

I would suggest two different updated sites, sounds better to me.

**Comment by vogella** [comment]
One thought, why not adjust your feature patch to the change in Mars? This would allow you to have one update site and one code basis.

**Comment by vogella** [comment]
FYI - Looks like the final fix is only in build I20141118-0830 and I tested with N20141117-2000. You should use the new build for any adjustments.

**Comment by vogella** [comment]
Tried with 4.5.0.N20141124-2000 but postfix completion still does not work without the patch. I think the feature patch should be in all cases an optional dependency.

**Comment by vogella** [comment]
@trylimits any update here? I'm planning to promote your plug-in a bit but that requires that it works in 4.4 and 4.5.

**Comment by trylimits** [comment]
> One thought, why not adjust your feature patch to the change in Mars? This would allow you to have one update site and one code basis.

This was the way to go.

The newest build of the plug-in (201412091906) does work on Luna and Mars (tested with build M3 20141113-0320).

Could you please verify for your Mars build (installation without the feature patch).

**Comment by vogella** [comment]
Awesome, will do.

On Tue, Dec 9, 2014 at 8:53 PM, trylimits notifications@github.com wrote:

> One thought, why not adjust your feature patch to the change in Mars? This
> would allow you to have one update site and one code basis.
> 
> This was the way to go.
> 
> The newest build of the plug-in (201412091906) does work on Luna and Mars
> (tested with build M3 20141113-0320).
> 
> Could you please verify for your Mars build (installation without the
> feature patch).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/trylimits/Eclipse-Postfix-Code-Completion/issues/11#issuecomment-66346210
> .

## 

Geschäftsführer

vogella GmbH

Haindaalwisch 17a, 22395 Hamburg
Amtsgericht Hamburg: HRB 127058
Geschäftsführer: Lars Vogel, Jennifer Nerlich de Vogel
USt-IdNr.: DE284122352
Fax (032) 221739404, Email: lars.vogel@vogella.com, Web:
http://www.vogella.com

**Comment by vogella** [comment]
Works fine in Build id: N20141206-2000. Thanks
